require 'factory_bot_rails'

include FactoryBot::Syntax::Methods

OrderItem.destroy_all
Order.destroy_all
Item.destroy_all
User.destroy_all

admin = create(:admin)
user = create(:user)
merchant_1 = create(:merchant)

merchant_2, merchant_3, merchant_4 = create_list(:merchant, 3)

inactive_merchant_1 = create(:inactive_merchant)
inactive_user_1 = create(:inactive_user)

item_1 = create(:item, user: merchant_1)
item_2 = create(:item, user: merchant_2)
item_3 = create(:item, user: merchant_3)
item_4 = create(:item, user: merchant_4)
create_list(:item, 10, user: merchant_1)

inactive_item_1 = create(:inactive_item, user: merchant_1)
inactive_item_2 = create(:inactive_item, user: inactive_merchant_1)

Random.new_seed
rng = Random.new

order = create(:completed_order, user: user)
create(:fulfilled_order_item, order: order, item: item_1, price: 1, quantity: 1, created_at: rng.rand(3).days.ago, updated_at: rng.rand(59).minutes.ago)
create(:fulfilled_order_item, order: order, item: item_2, price: 2, quantity: 1, created_at: rng.rand(23).hour.ago, updated_at: rng.rand(59).minutes.ago)
create(:fulfilled_order_item, order: order, item: item_3, price: 3, quantity: 1, created_at: rng.rand(5).days.ago, updated_at: rng.rand(59).minutes.ago)
create(:fulfilled_order_item, order: order, item: item_4, price: 4, quantity: 1, created_at: rng.rand(23).hour.ago, updated_at: rng.rand(59).minutes.ago)

order = create(:order, user: user)
create(:order_item, order: order, item: item_1, price: 1, quantity: 1)
create(:fulfilled_order_item, order: order, item: item_2, price: 2, quantity: 1, created_at: rng.rand(23).days.ago, updated_at: rng.rand(23).hours.ago)

order = create(:cancelled_order, user: user)
create(:order_item, order: order, item: item_2, price: 2, quantity: 1, created_at: rng.rand(23).hour.ago, updated_at: rng.rand(59).minutes.ago)
create(:order_item, order: order, item: item_3, price: 3, quantity: 1, created_at: rng.rand(23).hour.ago, updated_at: rng.rand(59).minutes.ago)

order = create(:completed_order, user: user)
create(:fulfilled_order_item, order: order, item: item_1, price: 1, quantity: 1, created_at: rng.rand(4).days.ago, updated_at: rng.rand(59).minutes.ago)
create(:fulfilled_order_item, order: order, item: item_2, price: 2, quantity: 1, created_at: rng.rand(23).hour.ago, updated_at: rng.rand(59).minutes.ago)


@user_1 = create(:user, city: 'Springfield', state: 'MO')
@user_2 = create(:user, city: 'Springfield', state: 'CO')
@user_3 = create(:user, city: 'Las Vegas', state: 'NV')
@user_4 = create(:user, city: 'Denver', state: 'CO')
user_2 = create(:user, state: 'CO')

@admin = create(:admin)

@m1 = create(:merchant)
@m2 = create(:merchant)
@m3 = create(:merchant)
@m4 = create(:merchant)
@m5 = create(:merchant)
@m6 = create(:merchant)
@m7 = create(:merchant)
@m8 = create(:merchant)
@m9 = create(:merchant)
@m10 = create(:merchant)
@m11 = create(:merchant)

@item_1 = create(:item, user: @m1)
@item_2 = create(:item, user: @m2)
@item_3 = create(:item, user: @m3)
@item_4 = create(:item, user: @m4)
@item_5 = create(:item, user: @m5)
@item_6 = create(:item, user: @m6)
@item_7 = create(:item, user: @m7)
@item_8 = create(:item, user: @m8)
@item_9 = create(:item, user: @m9)
@item_10 = create(:item, user: @m10)
@item_11 = create(:item, user: @m11)

@order_1 = create(:completed_order, user: @user_1)
@oi_1 = create(:fulfilled_order_item, order: @order_1, item: @item_1, quantity: 10, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_1_1 = create(:completed_order, user: @user_1)
@oi_1_1 = create(:fulfilled_order_item, order: @order_1_1, item: @item_1, quantity: 1, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_1_2 = create(:completed_order, user: @user_1)
@oi_1_2 = create(:fulfilled_order_item, order: @order_1_2, item: @item_1, quantity: 1, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_1_3 = create(:completed_order, user: @user_1)
@oi_1_3 = create(:fulfilled_order_item, order: @order_1_3, item: @item_1, quantity: 1, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_1_4 = create(:completed_order, user: @user_1)
@oi_1_4 = create(:fulfilled_order_item, order: @order_1_4, item: @item_1, quantity: 1, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_1_5 = create(:completed_order, user: @user_1)
@oi_1_5 = create(:fulfilled_order_item, order: @order_1_5, item: @item_1, quantity: 1, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_1_6 = create(:completed_order, user: @user_1)
@oi_1_6 = create(:fulfilled_order_item, order: @order_1_6, item: @item_1, quantity: 1, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_1_7 = create(:completed_order, user: @user_1)
@oi_1_7 = create(:fulfilled_order_item, order: @order_1_7, item: @item_1, quantity: 1, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_1_8 = create(:completed_order, user: @user_1)
@oi_1_8 = create(:fulfilled_order_item, order: @order_1_8, item: @item_1, quantity: 1, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_1_9 = create(:completed_order, user: @user_1)
@oi_1_9 = create(:fulfilled_order_item, order: @order_1_9, item: @item_1, quantity: 1, created_at: 12.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)

@order_2 = create(:completed_order, user: @user_1)
@oi_2 = create(:fulfilled_order_item, order: @order_2, item: @item_2, quantity: 9, created_at: 11.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_2_1 = create(:completed_order, user: @user_1)
@oi_2_1 = create(:fulfilled_order_item, order: @order_2_1, item: @item_2, quantity: 1, created_at: 11.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_2_2 = create(:completed_order, user: @user_1)
@oi_2_2 = create(:fulfilled_order_item, order: @order_2_2, item: @item_2, quantity: 1, created_at: 11.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_2_3 = create(:completed_order, user: @user_1)
@oi_2_3 = create(:fulfilled_order_item, order: @order_2_3, item: @item_2, quantity: 1, created_at: 11.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_2_4 = create(:completed_order, user: @user_1)
@oi_2_4 = create(:fulfilled_order_item, order: @order_2_4, item: @item_2, quantity: 1, created_at: 11.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_2_5 = create(:completed_order, user: @user_1)
@oi_2_5 = create(:fulfilled_order_item, order: @order_2_5, item: @item_2, quantity: 1, created_at: 11.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_2_6 = create(:completed_order, user: @user_1)
@oi_2_6 = create(:fulfilled_order_item, order: @order_2_6, item: @item_2, quantity: 1, created_at: 11.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_2_7 = create(:completed_order, user: @user_1)
@oi_2_7 = create(:fulfilled_order_item, order: @order_2_7, item: @item_2, quantity: 1, created_at: 11.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)
@order_2_8 = create(:completed_order, user: @user_1)
@oi_2_8 = create(:fulfilled_order_item, order: @order_2_8, item: @item_2, quantity: 1, created_at: 11.days.ago - 1.hour - 12.minutes - 30.seconds, updated_at: 1.days.ago - 9.minutes - 20.seconds)

@order_3 = create(:completed_order, user: @user_2)
@oi_3 = create(:fulfilled_order_item, order: @order_3, item: @item_3, quantity: 8, created_at: 10.days.ago, updated_at: 1.days.ago)
@order_3_1 = create(:completed_order, user: @user_2)
@oi_3_1 = create(:fulfilled_order_item, order: @order_3_1, item: @item_3, quantity: 1, created_at: 10.days.ago, updated_at: 1.days.ago)
@order_3_2 = create(:completed_order, user: @user_2)
@oi_3_2 = create(:fulfilled_order_item, order: @order_3_2, item: @item_3, quantity: 1, created_at: 10.days.ago, updated_at: 1.days.ago)
@order_3_3 = create(:completed_order, user: @user_2)
@oi_3_3 = create(:fulfilled_order_item, order: @order_3_3, item: @item_3, quantity: 1, created_at: 10.days.ago, updated_at: 1.days.ago)
@order_3_4 = create(:completed_order, user: @user_2)
@oi_3_4 = create(:fulfilled_order_item, order: @order_3_4, item: @item_3, quantity: 1, created_at: 10.days.ago, updated_at: 1.days.ago)
@order_3_5 = create(:completed_order, user: @user_2)
@oi_3_5 = create(:fulfilled_order_item, order: @order_3_5, item: @item_3, quantity: 1, created_at: 10.days.ago, updated_at: 1.days.ago)
@order_3_6 = create(:completed_order, user: @user_2)
@oi_3_6 = create(:fulfilled_order_item, order: @order_3_6, item: @item_3, quantity: 1, created_at: 10.days.ago, updated_at: 1.days.ago)
@order_3_7 = create(:completed_order, user: @user_2)
@oi_3_7 = create(:fulfilled_order_item, order: @order_3_7, item: @item_3, quantity: 1, created_at: 10.days.ago, updated_at: 1.days.ago)

@order_4 = create(:completed_order, user: @user_3)
@oi_4 = create(:fulfilled_order_item, order: @order_4, item: @item_4, quantity: 7, created_at: 9.days.ago, updated_at: 1.days.ago)
@order_4_1 = create(:completed_order, user: @user_3)
@oi_4_1 = create(:fulfilled_order_item, order: @order_4_1, item: @item_4, quantity: 1, created_at: 9.days.ago, updated_at: 1.days.ago)
@order_4_2 = create(:completed_order, user: @user_3)
@oi_4_2 = create(:fulfilled_order_item, order: @order_4_2, item: @item_4, quantity: 1, created_at: 9.days.ago, updated_at: 1.days.ago)
@order_4_3 = create(:completed_order, user: @user_3)
@oi_4_3 = create(:fulfilled_order_item, order: @order_4_3, item: @item_4, quantity: 1, created_at: 9.days.ago, updated_at: 1.days.ago)
@order_4_4 = create(:completed_order, user: @user_3)
@oi_4_4 = create(:fulfilled_order_item, order: @order_4_4, item: @item_4, quantity: 1, created_at: 9.days.ago, updated_at: 1.days.ago)
@order_4_5 = create(:completed_order, user: @user_3)
@oi_4_5 = create(:fulfilled_order_item, order: @order_4_5, item: @item_4, quantity: 1, created_at: 9.days.ago, updated_at: 1.days.ago)
@order_4_6 = create(:completed_order, user: @user_3)
@oi_4_6 = create(:fulfilled_order_item, order: @order_4_6, item: @item_4, quantity: 1, created_at: 9.days.ago, updated_at: 1.days.ago)

@order_5 = create(:completed_order, user: @user_4)
@oi_5 = create(:fulfilled_order_item, order: @order_5, item: @item_5, quantity: 6, created_at: 8.days.ago, updated_at: 1.days.ago)
@order_5_1 = create(:completed_order, user: @user_4)
@oi_5_1 = create(:fulfilled_order_item, order: @order_5_1, item: @item_5, quantity: 1, created_at: 8.days.ago, updated_at: 1.days.ago)
@order_5_2 = create(:completed_order, user: @user_4)
@oi_5_2 = create(:fulfilled_order_item, order: @order_5_2, item: @item_5, quantity: 1, created_at: 8.days.ago, updated_at: 1.days.ago)
@order_5_3 = create(:completed_order, user: @user_4)
@oi_5_3 = create(:fulfilled_order_item, order: @order_5_3, item: @item_5, quantity: 1, created_at: 8.days.ago, updated_at: 1.days.ago)
@order_5_4 = create(:completed_order, user: @user_4)
@oi_5_4 = create(:fulfilled_order_item, order: @order_5_4, item: @item_5, quantity: 1, created_at: 8.days.ago, updated_at: 1.days.ago)
@order_5_5 = create(:completed_order, user: @user_4)
@oi_5_5 = create(:fulfilled_order_item, order: @order_5_5, item: @item_5, quantity: 1, created_at: 8.days.ago, updated_at: 1.days.ago)

@order_6 = create(:completed_order, user: @user_4)
@oi_6 = create(:fulfilled_order_item, order: @order_6, item: @item_6, quantity: 5, created_at: 7.days.ago, updated_at: 1.days.ago)
@order_6_1 = create(:completed_order, user: @user_4)
@oi_6_1 = create(:fulfilled_order_item, order: @order_6_1, item: @item_6, quantity: 1, created_at: 7.days.ago, updated_at: 1.days.ago)
@order_6_2 = create(:completed_order, user: @user_4)
@oi_6_2 = create(:fulfilled_order_item, order: @order_6_2, item: @item_6, quantity: 1, created_at: 7.days.ago, updated_at: 1.days.ago)
@order_6_3 = create(:completed_order, user: @user_4)
@oi_6_3 = create(:fulfilled_order_item, order: @order_6_3, item: @item_6, quantity: 1, created_at: 7.days.ago, updated_at: 1.days.ago)
@order_6_4 = create(:completed_order, user: @user_4)
@oi_6_4 = create(:fulfilled_order_item, order: @order_6_4, item: @item_6, quantity: 1, created_at: 7.days.ago, updated_at: 1.days.ago)

@order_7 = create(:completed_order, user: @user_1)
@oi_7 = create(:fulfilled_order_item, order: @order_7, item: @item_7, quantity: 4, created_at: 6.days.ago, updated_at: 1.days.ago)
@order_7_1 = create(:completed_order, user: @user_1)
@oi_7_1 = create(:fulfilled_order_item, order: @order_7_1, item: @item_7, quantity: 1, created_at: 6.days.ago, updated_at: 1.days.ago)
@order_7_2 = create(:completed_order, user: @user_1)
@oi_7_2 = create(:fulfilled_order_item, order: @order_7_2, item: @item_7, quantity: 1, created_at: 6.days.ago, updated_at: 1.days.ago)
@order_7_3 = create(:completed_order, user: @user_1)
@oi_7_3 = create(:fulfilled_order_item, order: @order_7_3, item: @item_7, quantity: 1, created_at: 6.days.ago, updated_at: 1.days.ago)

@order_8 = create(:completed_order, user: @user_2)
@oi_8 = create(:fulfilled_order_item, order: @order_8, item: @item_8, quantity: 3, created_at: 5.days.ago, updated_at: 1.days.ago)
@order_8_1 = create(:completed_order, user: @user_2)
@oi_8_1 = create(:fulfilled_order_item, order: @order_8_1, item: @item_8, quantity: 1, created_at: 5.days.ago, updated_at: 1.days.ago)
@order_8_2 = create(:completed_order, user: @user_2)
@oi_8_2 = create(:fulfilled_order_item, order: @order_8_2, item: @item_8, quantity: 1, created_at: 5.days.ago, updated_at: 1.days.ago)

@order_9 = create(:completed_order, user: @user_2)
@oi_9 = create(:fulfilled_order_item, order: @order_9, item: @item_9, quantity: 2, created_at: 4.days.ago, updated_at: 1.days.ago)
@order_9_1 = create(:completed_order, user: @user_2)
@oi_9_1 = create(:fulfilled_order_item, order: @order_9_1, item: @item_9, quantity: 1, created_at: 4.days.ago, updated_at: 1.days.ago)

@order_10 = create(:completed_order, user: @user_4)
@oi_10 = create(:fulfilled_order_item, order: @order_10, item: @item_10, quantity: 2, created_at: 3.days.ago, updated_at: 1.days.ago)

@order_11 = create(:completed_order, user: @user_4)
@oi_11 = create(:fulfilled_order_item, order: @order_11, item: @item_11, quantity: 1, created_at: 2.days.ago, updated_at: 1.days.ago)


@order_a = create(:completed_order, user: @user_1)
@oi_a = create(:fulfilled_order_item, order: @order_a, item: @item_1, quantity: 10, created_at: 42.days.ago, updated_at: 31.days.ago)
@order_a_1 = create(:completed_order, user: @user_1)
@oi_a_1 = create(:fulfilled_order_item, order: @order_a_1, item: @item_1, quantity: 1, created_at: 42.days.ago, updated_at: 31.days.ago)
@order_a_2 = create(:completed_order, user: @user_1)
@oi_a_2 = create(:fulfilled_order_item, order: @order_a_2, item: @item_1, quantity: 1, created_at: 42.days.ago, updated_at: 31.days.ago)
@order_a_3 = create(:completed_order, user: @user_1)
@oi_a_3 = create(:fulfilled_order_item, order: @order_a_3, item: @item_1, quantity: 1, created_at: 42.days.ago, updated_at: 31.days.ago)
@order_a_4 = create(:completed_order, user: @user_1)
@oi_a_4 = create(:fulfilled_order_item, order: @order_a_4, item: @item_1, quantity: 1, created_at: 42.days.ago, updated_at: 31.days.ago)
@order_a_5 = create(:completed_order, user: @user_1)
@oi_a_5 = create(:fulfilled_order_item, order: @order_a_5, item: @item_1, quantity: 1, created_at: 42.days.ago, updated_at: 31.days.ago)
@order_a_6 = create(:completed_order, user: @user_1)
@oi_a_6 = create(:fulfilled_order_item, order: @order_a_6, item: @item_1, quantity: 1, created_at: 42.days.ago, updated_at: 31.days.ago)
@order_a_7 = create(:completed_order, user: @user_1)
@oi_a_7 = create(:fulfilled_order_item, order: @order_a_7, item: @item_1, quantity: 1, created_at: 42.days.ago, updated_at: 31.days.ago)
@order_a_8 = create(:completed_order, user: @user_1)
@oi_a_8 = create(:fulfilled_order_item, order: @order_a_8, item: @item_1, quantity: 1, created_at: 42.days.ago, updated_at: 31.days.ago)
@order_a_9 = create(:completed_order, user: @user_1)
@oi_a_9 = create(:fulfilled_order_item, order: @order_a_9, item: @item_1, quantity: 1, created_at: 42.days.ago, updated_at: 31.days.ago)

@order_b = create(:completed_order, user: @user_1)
@oi_b = create(:fulfilled_order_item, order: @order_b, item: @item_2, quantity: 9, created_at: 41.days.ago, updated_at: 31.days.ago)
@order_b_1 = create(:completed_order, user: @user_1)
@oi_b_1 = create(:fulfilled_order_item, order: @order_b_1, item: @item_2, quantity: 1, created_at: 41.days.ago, updated_at: 31.days.ago)
@order_b_2 = create(:completed_order, user: @user_1)
@oi_b_2 = create(:fulfilled_order_item, order: @order_b_2, item: @item_2, quantity: 1, created_at: 41.days.ago, updated_at: 31.days.ago)
@order_b_3 = create(:completed_order, user: @user_1)
@oi_b_3 = create(:fulfilled_order_item, order: @order_b_3, item: @item_2, quantity: 1, created_at: 41.days.ago, updated_at: 31.days.ago)
@order_b_4 = create(:completed_order, user: @user_1)
@oi_b_4 = create(:fulfilled_order_item, order: @order_b_4, item: @item_2, quantity: 1, created_at: 41.days.ago, updated_at: 31.days.ago)
@order_b_5 = create(:completed_order, user: @user_1)
@oi_b_5 = create(:fulfilled_order_item, order: @order_b_5, item: @item_2, quantity: 1, created_at: 41.days.ago, updated_at: 31.days.ago)
@order_b_6 = create(:completed_order, user: @user_1)
@oi_b_6 = create(:fulfilled_order_item, order: @order_b_6, item: @item_2, quantity: 1, created_at: 41.days.ago, updated_at: 31.days.ago)
@order_b_7 = create(:completed_order, user: @user_1)
@oi_b_7 = create(:fulfilled_order_item, order: @order_b_7, item: @item_2, quantity: 1, created_at: 41.days.ago, updated_at: 31.days.ago)
@order_b_8 = create(:completed_order, user: @user_1)
@oi_b_8 = create(:fulfilled_order_item, order: @order_b_8, item: @item_2, quantity: 1, created_at: 41.days.ago, updated_at: 31.days.ago)

@order_c = create(:completed_order, user: @user_2)
@oi_c = create(:fulfilled_order_item, order: @order_c, item: @item_3, quantity: 8, created_at: 40.days.ago, updated_at: 31.days.ago)
@order_c_1 = create(:completed_order, user: @user_2)
@oi_c_1 = create(:fulfilled_order_item, order: @order_c_1, item: @item_3, quantity: 1, created_at: 40.days.ago, updated_at: 31.days.ago)
@order_c_2 = create(:completed_order, user: @user_2)
@oi_c_2 = create(:fulfilled_order_item, order: @order_c_2, item: @item_3, quantity: 1, created_at: 40.days.ago, updated_at: 31.days.ago)
@order_c_3 = create(:completed_order, user: @user_2)
@oi_c_3 = create(:fulfilled_order_item, order: @order_c_3, item: @item_3, quantity: 1, created_at: 40.days.ago, updated_at: 31.days.ago)
@order_c_4 = create(:completed_order, user: @user_2)
@oi_c_4 = create(:fulfilled_order_item, order: @order_c_4, item: @item_3, quantity: 1, created_at: 40.days.ago, updated_at: 31.days.ago)
@order_c_5 = create(:completed_order, user: @user_2)
@oi_c_5 = create(:fulfilled_order_item, order: @order_c_5, item: @item_3, quantity: 1, created_at: 40.days.ago, updated_at: 31.days.ago)
@order_c_6 = create(:completed_order, user: @user_2)
@oi_c_6 = create(:fulfilled_order_item, order: @order_c_6, item: @item_3, quantity: 1, created_at: 40.days.ago, updated_at: 31.days.ago)
@order_c_7 = create(:completed_order, user: @user_2)
@oi_c_7 = create(:fulfilled_order_item, order: @order_c_7, item: @item_3, quantity: 1, created_at: 40.days.ago, updated_at: 31.days.ago)

@order_d = create(:completed_order, user: @user_3)
@oi_d = create(:fulfilled_order_item, order: @order_d, item: @item_4, quantity: 7, created_at: 39.days.ago, updated_at: 31.days.ago)
@order_d_1 = create(:completed_order, user: @user_3)
@oi_d_1 = create(:fulfilled_order_item, order: @order_d_1, item: @item_4, quantity: 1, created_at: 39.days.ago, updated_at: 31.days.ago)
@order_d_2 = create(:completed_order, user: @user_3)
@oi_d_2 = create(:fulfilled_order_item, order: @order_d_2, item: @item_4, quantity: 1, created_at: 39.days.ago, updated_at: 31.days.ago)
@order_d_3 = create(:completed_order, user: @user_3)
@oi_d_3 = create(:fulfilled_order_item, order: @order_d_3, item: @item_4, quantity: 1, created_at: 39.days.ago, updated_at: 31.days.ago)
@order_d_4 = create(:completed_order, user: @user_3)
@oi_d_4 = create(:fulfilled_order_item, order: @order_d_4, item: @item_4, quantity: 1, created_at: 39.days.ago, updated_at: 31.days.ago)
@order_d_5 = create(:completed_order, user: @user_3)
@oi_d_5 = create(:fulfilled_order_item, order: @order_d_5, item: @item_4, quantity: 1, created_at: 39.days.ago, updated_at: 31.days.ago)
@order_d_6 = create(:completed_order, user: @user_3)
@oi_d_6 = create(:fulfilled_order_item, order: @order_d_6, item: @item_4, quantity: 1, created_at: 39.days.ago, updated_at: 31.days.ago)

@order_e = create(:completed_order, user: @user_4)
@oi_e = create(:fulfilled_order_item, order: @order_e, item: @item_5, quantity: 6, created_at: 38.days.ago, updated_at: 31.days.ago)
@order_e_1 = create(:completed_order, user: @user_4)
@oi_e_1 = create(:fulfilled_order_item, order: @order_e_1, item: @item_5, quantity: 1, created_at: 38.days.ago, updated_at: 31.days.ago)
@order_e_2 = create(:completed_order, user: @user_4)
@oi_e_2 = create(:fulfilled_order_item, order: @order_e_2, item: @item_5, quantity: 1, created_at: 38.days.ago, updated_at: 31.days.ago)
@order_e_3 = create(:completed_order, user: @user_4)
@oi_e_3 = create(:fulfilled_order_item, order: @order_e_3, item: @item_5, quantity: 1, created_at: 38.days.ago, updated_at: 31.days.ago)
@order_e_4 = create(:completed_order, user: @user_4)
@oi_e_4 = create(:fulfilled_order_item, order: @order_e_4, item: @item_5, quantity: 1, created_at: 38.days.ago, updated_at: 31.days.ago)
@order_e_5 = create(:completed_order, user: @user_4)
@oi_e_5 = create(:fulfilled_order_item, order: @order_e_5, item: @item_5, quantity: 1, created_at: 38.days.ago, updated_at: 31.days.ago)

@order_f = create(:completed_order, user: @user_4)
@oi_f = create(:fulfilled_order_item, order: @order_f, item: @item_6, quantity: 5, created_at: 37.days.ago, updated_at: 31.days.ago)
@order_f_1 = create(:completed_order, user: @user_4)
@oi_f_1 = create(:fulfilled_order_item, order: @order_f_1, item: @item_6, quantity: 1, created_at: 37.days.ago, updated_at: 31.days.ago)
@order_f_2 = create(:completed_order, user: @user_4)
@oi_f_2 = create(:fulfilled_order_item, order: @order_f_2, item: @item_6, quantity: 1, created_at: 37.days.ago, updated_at: 31.days.ago)
@order_f_3 = create(:completed_order, user: @user_4)
@oi_f_3 = create(:fulfilled_order_item, order: @order_f_3, item: @item_6, quantity: 1, created_at: 37.days.ago, updated_at: 31.days.ago)
@order_f_4 = create(:completed_order, user: @user_4)
@oi_f_4 = create(:fulfilled_order_item, order: @order_f_4, item: @item_6, quantity: 1, created_at: 37.days.ago, updated_at: 31.days.ago)

@order_g = create(:completed_order, user: @user_1)
@oi_g = create(:fulfilled_order_item, order: @order_g, item: @item_7, quantity: 4, created_at: 36.days.ago, updated_at: 31.days.ago)
@order_g_1 = create(:completed_order, user: @user_1)
@oi_g_1 = create(:fulfilled_order_item, order: @order_g_1, item: @item_7, quantity: 1, created_at: 36.days.ago, updated_at: 31.days.ago)
@order_g_2 = create(:completed_order, user: @user_1)
@oi_g_2 = create(:fulfilled_order_item, order: @order_g_2, item: @item_7, quantity: 1, created_at: 36.days.ago, updated_at: 31.days.ago)
@order_g_3 = create(:completed_order, user: @user_1)
@oi_g_3 = create(:fulfilled_order_item, order: @order_g_3, item: @item_7, quantity: 1, created_at: 36.days.ago, updated_at: 31.days.ago)

@order_h = create(:completed_order, user: @user_2)
@oi_h = create(:fulfilled_order_item, order: @order_h, item: @item_8, quantity: 3, created_at: 35.days.ago, updated_at: 31.days.ago)
@order_h_1 = create(:completed_order, user: @user_2)
@oi_h_1 = create(:fulfilled_order_item, order: @order_h_1, item: @item_8, quantity: 1, created_at: 35.days.ago, updated_at: 31.days.ago)
@order_h_2 = create(:completed_order, user: @user_2)
@oi_h_2 = create(:fulfilled_order_item, order: @order_h_2, item: @item_8, quantity: 1, created_at: 35.days.ago, updated_at: 31.days.ago)

@order_i = create(:completed_order, user: @user_2)
@oi_i = create(:fulfilled_order_item, order: @order_i, item: @item_9, quantity: 2, created_at: 34.days.ago, updated_at: 31.days.ago)
@order_i_1 = create(:completed_order, user: @user_2)
@oi_i_1 = create(:fulfilled_order_item, order: @order_i_1, item: @item_9, quantity: 1, created_at: 34.days.ago, updated_at: 31.days.ago)

@order_j = create(:completed_order, user: @user_4)
@oi_j = create(:fulfilled_order_item, order: @order_j, item: @item_10, quantity: 2, created_at: 33.days.ago, updated_at: 31.days.ago)

@order_k = create(:completed_order, user: @user_4)
@oi_k = create(:fulfilled_order_item, order: @order_k, item: @item_11, quantity: 1, created_at: 32.days.ago, updated_at: 31.days.ago)

item_1 = create(:item, user: @m1)
item_2 = create(:item, user: @m2)
item_3 = create(:item, user: @m3)
item_4 = create(:item, user: @m4)
item_5 = create(:item, user: @m5)
item_6 = create(:item, user: @m6)

    order_1_a = create(:completed_order, user: @user_1)
    oi_1_a = create(:fulfilled_order_item, order: order_1_a, item: item_1, quantity: 10, created_at: 12.days.ago, updated_at: 1.days.ago)

    order_2_a = create(:completed_order, user: @user_1)
    oi_2_a = create(:fulfilled_order_item, order: order_2_a, item: item_2, quantity: 10, created_at: 11.days.ago, updated_at: 1.days.ago)

    order_3_a = create(:completed_order, user: @user_1)
    oi_3_a = create(:fulfilled_order_item, order: order_3_a, item: item_3, quantity: 10, created_at: 10.days.ago, updated_at: 1.days.ago)

    order_4_a = create(:completed_order, user: @user_1)
    oi_4_a = create(:fulfilled_order_item, order: order_4_a, item: item_4, quantity: 10, created_at: 9.days.ago, updated_at: 1.days.ago)

    order_5_a = create(:completed_order, user: @user_1)
    oi_5_a = create(:fulfilled_order_item, order: order_5_a, item: item_5, quantity: 10, created_at: 8.days.ago, updated_at: 1.days.ago)

    order_6_a = create(:completed_order, user: @user_1)
    oi_6_a = create(:fulfilled_order_item, order: order_6_a, item: item_6, quantity: 10, created_at: 7.days.ago, updated_at: 1.days.ago)


    order_1_b = create(:completed_order, user: user_2)
    oi_1_b = create(:fulfilled_order_item, order: order_1_b, item: item_2, quantity: 10, created_at: 1.days.ago, updated_at: 4.hours.ago)

    order_2_b = create(:completed_order, user: user_2)
    oi_2_b = create(:fulfilled_order_item, order: order_2_b, item: item_2, quantity: 10, created_at: 1.days.ago, updated_at: 4.hours.ago)

    order_3_b = create(:completed_order, user: user_2)
    oi_3_b = create(:fulfilled_order_item, order: order_3_b, item: item_2, quantity: 10, created_at: 1.days.ago, updated_at: 4.hours.ago)

    order_4_b = create(:completed_order, user: user_2)
    oi_4_b = create(:fulfilled_order_item, order: order_4_b, item: item_3, quantity: 10, created_at: 1.days.ago, updated_at: 1.hours.ago)

    order_5_b = create(:completed_order, user: user_2)
    oi_5_b = create(:fulfilled_order_item, order: order_5_b, item: item_3, quantity: 10, created_at: 1.days.ago, updated_at: 1.hours.ago)

    order_6_b = create(:completed_order, user: user_2)
    oi_6_b = create(:fulfilled_order_item, order: order_6_b, item: item_3, quantity: 10, created_at: 1.days.ago, updated_at: 1.hours.ago)
